### ISSUE TITLE
[Q] Is it possible to set which frame to start playback from?

### ISSUE THREAD

**Issue by danielmkarlsson** [redFrik/yetanotheroscmovieplayer#1]
Hi redFrik.
This is amazing. I love this. This is exactly what I need. Thank you for making this.

I have a question: It is possible to set \start_frame or \start_pos? The latter of these I am imagining as a float between zero and one.

Again, amazing superBestest application __ever in time!__ 
I have a workaround no problem, I am just chopping up my file in small chunks.

All the best

Daniel

**Comment by redFrik** [comment]
thanks, glad you like it.

good idea.  both of these should be very easy to add.  i'll get to it later today.

**Comment by redFrik** [comment]
Now implemented /frame and /position (also added /exit). Please give it a go.
Note that jumping backwards in time might work better or worse depending on which video codec you are using.

**Comment by danielmkarlsson** [comment]
Woot, woot!
Works like a charm at lower speeds.
If I push it past this point I am consistently able to make it choke and crash:

```
n= NetAddr("127.0.0.1", 61000);
n.sendMsg(\start, "/Your/Path/here/NeverGonnaGiveYouUp.mov", 1, 0)
~pos = Pstutter(5,Pwhite(0.0, 1.0)).asStream;
(
Pdef(0,
    Pbind(*[
    type: \r,
    rps: Phprand(5, 11),
    dur: Pwhite(1/11,1/9),
    pos: Pstutter(Pkey(\rps),Pfunc({n.sendMsg(\position, ~pos.next)})),
])
).play
)
```

That is totally fine for my purposes.
Really enjoying zipping around in video files.
PhotoJPEG works better for sure.
Curious to try HAP next.
Thank you so much for adding this feature.
